"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.complex_relation_leg_request import ComplexRelationLegRequest


class TestComplexRelationLegRequest(unittest.TestCase):
    """ComplexRelationLegRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplexRelationLegRequest(self):
        """Test ComplexRelationLegRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ComplexRelationLegRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
