"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.relation_impl import RelationImpl
globals()['RelationImpl'] = RelationImpl
from collibra_core.model.paged_response_relation import PagedResponseRelation


class TestPagedResponseRelation(unittest.TestCase):
    """PagedResponseRelation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagedResponseRelation(self):
        """Test PagedResponseRelation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PagedResponseRelation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
