"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.rating import Rating
globals()['Rating'] = Rating
from collibra_core.model.paged_response_rating import PagedResponseRating


class TestPagedResponseRating(unittest.TestCase):
    """PagedResponseRating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagedResponseRating(self):
        """Test PagedResponseRating"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PagedResponseRating()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
