"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.dropdown_value import DropdownValue
from collibra_core.model.option_value import OptionValue
from collibra_core.model.resource_reference import ResourceReference
globals()['DropdownValue'] = DropdownValue
globals()['OptionValue'] = OptionValue
globals()['ResourceReference'] = ResourceReference
from collibra_core.model.form_property import FormProperty


class TestFormProperty(unittest.TestCase):
    """FormProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormProperty(self):
        """Test FormProperty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FormProperty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
