"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.attribute import Attribute
globals()['Attribute'] = Attribute
from collibra_core.model.attribute_paged_response import AttributePagedResponse


class TestAttributePagedResponse(unittest.TestCase):
    """AttributePagedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributePagedResponse(self):
        """Test AttributePagedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttributePagedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
