"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.articulation_rule_impl import ArticulationRuleImpl
from collibra_core.model.assigned_characteristic_type import AssignedCharacteristicType
from collibra_core.model.named_described_resource_reference import NamedDescribedResourceReference
from collibra_core.model.named_resource_reference_impl import NamedResourceReferenceImpl
from collibra_core.model.scope_impl import ScopeImpl
globals()['ArticulationRuleImpl'] = ArticulationRuleImpl
globals()['AssignedCharacteristicType'] = AssignedCharacteristicType
globals()['NamedDescribedResourceReference'] = NamedDescribedResourceReference
globals()['NamedResourceReferenceImpl'] = NamedResourceReferenceImpl
globals()['ScopeImpl'] = ScopeImpl
from collibra_core.model.assignment_impl import AssignmentImpl


class TestAssignmentImpl(unittest.TestCase):
    """AssignmentImpl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssignmentImpl(self):
        """Test AssignmentImpl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssignmentImpl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
