"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.activity_impl import ActivityImpl
globals()['ActivityImpl'] = ActivityImpl
from collibra_core.model.activity_paged_response import ActivityPagedResponse


class TestActivityPagedResponse(unittest.TestCase):
    """ActivityPagedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityPagedResponse(self):
        """Test ActivityPagedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivityPagedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
