"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.attribute_type import AttributeType
globals()['AttributeType'] = AttributeType
from collibra_core.model.attribute_type_paged_response import AttributeTypePagedResponse


class TestAttributeTypePagedResponse(unittest.TestCase):
    """AttributeTypePagedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributeTypePagedResponse(self):
        """Test AttributeTypePagedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttributeTypePagedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
