"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.attachment_impl import AttachmentImpl
globals()['AttachmentImpl'] = AttachmentImpl
from collibra_core.model.attachment_paged_response import AttachmentPagedResponse


class TestAttachmentPagedResponse(unittest.TestCase):
    """AttachmentPagedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentPagedResponse(self):
        """Test AttachmentPagedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentPagedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
