"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.view_permission_impl import ViewPermissionImpl
globals()['ViewPermissionImpl'] = ViewPermissionImpl
from collibra_core.model.paged_response_view_permission import PagedResponseViewPermission


class TestPagedResponseViewPermission(unittest.TestCase):
    """PagedResponseViewPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagedResponseViewPermission(self):
        """Test PagedResponseViewPermission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PagedResponseViewPermission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
