"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import collibra_core
from collibra_core.api.files_api import FilesApi  # noqa: E501


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_files(self):
        """Test case for add_files

        Upload files  # noqa: E501
        """
        pass

    def test_get_file(self):
        """Test case for get_file

        Download file  # noqa: E501
        """
        pass

    def test_get_file_info(self):
        """Test case for get_file_info

        Get file information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
