"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import collibra_core
from collibra_core.model.named_resource_reference_impl import NamedResourceReferenceImpl
globals()['NamedResourceReferenceImpl'] = NamedResourceReferenceImpl
from collibra_core.model.domain_type_impl import DomainTypeImpl


class TestDomainTypeImpl(unittest.TestCase):
    """DomainTypeImpl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainTypeImpl(self):
        """Test DomainTypeImpl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DomainTypeImpl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
