"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from collibra_core.api_client import ApiClient, Endpoint
from collibra_core.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from collibra_core.model.attachment_impl import AttachmentImpl
from collibra_core.model.attachment_paged_response import AttachmentPagedResponse


class AttachmentsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __add_attachment(
            self,
            **kwargs
        ):
            """Add attachment  # noqa: E501

            Adds new attachment.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.add_attachment(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                file (file_type): the file - attachment content. [optional]
                file_name (str): the display name of the file of this attachment. [optional]
                resource_type (str): the type of the resource the attachment should refer to. An attachment can be added on those resource types: User, Community, Domain, Asset, Role, ValidationRule, Workflow.. [optional]
                resource_id (str): the id of the resource the attachment should refer to. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                AttachmentImpl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.add_attachment = Endpoint(
            settings={
                'response_type': (AttachmentImpl,),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/attachments',
                'operation_id': 'add_attachment',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'file',
                    'file_name',
                    'resource_type',
                    'resource_id',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                    'resource_type',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('resource_type',): {

                        "VIEW": "View",
                        "ASSET": "Asset",
                        "COMMUNITY": "Community",
                        "DOMAIN": "Domain",
                        "ASSETTYPE": "AssetType",
                        "DOMAINTYPE": "DomainType",
                        "STATUS": "Status",
                        "USER": "User",
                        "CLASSIFICATIONMATCH": "ClassificationMatch",
                        "USERGROUP": "UserGroup",
                        "ATTRIBUTE": "Attribute",
                        "STRINGATTRIBUTE": "StringAttribute",
                        "SCRIPTATTRIBUTE": "ScriptAttribute",
                        "BOOLEANATTRIBUTE": "BooleanAttribute",
                        "DATEATTRIBUTE": "DateAttribute",
                        "NUMERICATTRIBUTE": "NumericAttribute",
                        "SINGLEVALUELISTATTRIBUTE": "SingleValueListAttribute",
                        "MULTIVALUELISTATTRIBUTE": "MultiValueListAttribute",
                        "COMMENT": "Comment",
                        "ATTACHMENT": "Attachment",
                        "RESPONSIBILITY": "Responsibility",
                        "WORKFLOW": "Workflow",
                        "JOB": "Job",
                        "RELATION": "Relation",
                        "RELATIONTYPE": "RelationType",
                        "COMPLEXRELATION": "ComplexRelation",
                        "COMPLEXRELATIONTYPE": "ComplexRelationType",
                        "ARTICULATIONRULE": "ArticulationRule",
                        "ASSIGNMENT": "Assignment",
                        "SCOPE": "Scope",
                        "RELATIONTRACE": "RelationTrace",
                        "VALIDATIONRULE": "ValidationRule",
                        "DATAQUALITYRULE": "DataQualityRule",
                        "DATAQUALITYMETRIC": "DataQualityMetric",
                        "ADDRESS": "Address",
                        "INSTANTMESSAGINGACCOUNT": "InstantMessagingAccount",
                        "EMAIL": "Email",
                        "PHONENUMBER": "PhoneNumber",
                        "WEBSITE": "Website",
                        "ACTIVITY": "Activity",
                        "FORMPROPERTY": "FormProperty",
                        "WORKFLOWTASK": "WorkflowTask",
                        "ACTIVITYCHANGE": "ActivityChange",
                        "WORKFLOWINSTANCE": "WorkflowInstance",
                        "ROLE": "Role",
                        "ATTRIBUTETYPE": "AttributeType",
                        "BOOLEANATTRIBUTETYPE": "BooleanAttributeType",
                        "DATEATTRIBUTETYPE": "DateAttributeType",
                        "DATETIMEATTRIBUTETYPE": "DateTimeAttributeType",
                        "MULTIVALUELISTATTRIBUTETYPE": "MultiValueListAttributeType",
                        "NUMERICATTRIBUTETYPE": "NumericAttributeType",
                        "SCRIPTATTRIBUTETYPE": "ScriptAttributeType",
                        "SINGLEVALUELISTATTRIBUTETYPE": "SingleValueListAttributeType",
                        "STRINGATTRIBUTETYPE": "StringAttributeType",
                        "VIEWSHARINGRULE": "ViewSharingRule",
                        "VIEWASSIGNMENTRULE": "ViewAssignmentRule",
                        "JDBCDRIVERFILE": "JdbcDriverFile",
                        "JDBCDRIVER": "JdbcDriver",
                        "JDBCINGESTIONPROPERTIES": "JdbcIngestionProperties",
                        "CSVINGESTIONPROPERTIES": "CsvIngestionProperties",
                        "EXCELINGESTIONPROPERTIES": "ExcelIngestionProperties",
                        "CONNECTIONSTRINGPARAMETER": "ConnectionStringParameter",
                        "ASSIGNEDCHARACTERISTICTYPE": "AssignedCharacteristicType",
                        "NOTIFICATION": "Notification",
                        "TAG": "Tag",
                        "COMPLEXRELATIONLEGTYPE": "ComplexRelationLegType",
                        "COMPLEXRELATIONATTRIBUTETYPE": "ComplexRelationAttributeType",
                        "COMPLEXRELATIONLEG": "ComplexRelationLeg",
                        "BASEDATATYPE": "BaseDataType",
                        "ADVANCEDDATATYPE": "AdvancedDataType",
                        "DIAGRAMPICTURE": "DiagramPicture",
                        "DIAGRAMPICTURESHARINGRULE": "DiagramPictureSharingRule",
                        "DIAGRAMPICTUREASSIGNMENTRULE": "DiagramPictureAssignmentRule",
                        "RATING": "Rating",
                        "CLASSIFICATION": "Classification"
                    },
                },
                'openapi_types': {
                    'file':
                        (file_type,),
                    'file_name':
                        (str,),
                    'resource_type':
                        (str,),
                    'resource_id':
                        (str,),
                },
                'attribute_map': {
                    'file': 'file',
                    'file_name': 'fileName',
                    'resource_type': 'resourceType',
                    'resource_id': 'resourceId',
                },
                'location_map': {
                    'file': 'form',
                    'file_name': 'form',
                    'resource_type': 'form',
                    'resource_id': 'form',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'multipart/form-data'
                ]
            },
            api_client=api_client,
            callable=__add_attachment
        )

        def __find_attachments(
            self,
            **kwargs
        ):
            """Find attachments  # noqa: E501

            Returns attachments matching the given search criteria. Only parameters that are specified in this request and have not <code>null</code> values are used for filtering. All other parameters are ignored. The returned attachments satisfy all constraints that are specified in this search criteria. By default a result containing 1000 attachments is returned.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.find_attachments(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                offset (int): The first result to retrieve. If not set (offset = <code>0</code>), results will be retrieved starting from row <code>0</code>.. [optional] if omitted the server will use the default value of 0
                limit (int): The maximum number of results to retrieve. If not set (limit = <code>0</code>), the default limit will be used.. [optional] if omitted the server will use the default value of 0
                file_name (str): The name of the file representing searched attachment.. [optional]
                file_content_type (str): The type of the content of the file representing searched attachment.. [optional]
                upload_date (int): The date of attachment upload. It is the timestamp (in UTC time standard).. [optional]
                user_id (str): The ID of the user who uploaded the attachment.. [optional]
                base_resource_id (str): The ID of the resource the attachment refers to.. [optional]
                sort_field (str): The field that should be used as reference for sorting.. [optional] if omitted the server will use the default value of "LAST_MODIFIED"
                sort_order (str): The order of sorting.. [optional] if omitted the server will use the default value of "DESC"
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                AttachmentPagedResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.find_attachments = Endpoint(
            settings={
                'response_type': (AttachmentPagedResponse,),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/attachments',
                'operation_id': 'find_attachments',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'offset',
                    'limit',
                    'file_name',
                    'file_content_type',
                    'upload_date',
                    'user_id',
                    'base_resource_id',
                    'sort_field',
                    'sort_order',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                    'sort_field',
                    'sort_order',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('sort_field',): {

                        "FILE_CONTENT_TYPE": "FILE_CONTENT_TYPE",
                        "CREATED_BY": "CREATED_BY",
                        "FILE_NAME": "FILE_NAME",
                        "CREATED_ON": "CREATED_ON",
                        "BASE_RESOURCE_ID": "BASE_RESOURCE_ID",
                        "LAST_MODIFIED": "LAST_MODIFIED"
                    },
                    ('sort_order',): {

                        "ASC": "ASC",
                        "DESC": "DESC"
                    },
                },
                'openapi_types': {
                    'offset':
                        (int,),
                    'limit':
                        (int,),
                    'file_name':
                        (str,),
                    'file_content_type':
                        (str,),
                    'upload_date':
                        (int,),
                    'user_id':
                        (str,),
                    'base_resource_id':
                        (str,),
                    'sort_field':
                        (str,),
                    'sort_order':
                        (str,),
                },
                'attribute_map': {
                    'offset': 'offset',
                    'limit': 'limit',
                    'file_name': 'fileName',
                    'file_content_type': 'fileContentType',
                    'upload_date': 'uploadDate',
                    'user_id': 'userId',
                    'base_resource_id': 'baseResourceId',
                    'sort_field': 'sortField',
                    'sort_order': 'sortOrder',
                },
                'location_map': {
                    'offset': 'query',
                    'limit': 'query',
                    'file_name': 'query',
                    'file_content_type': 'query',
                    'upload_date': 'query',
                    'user_id': 'query',
                    'base_resource_id': 'query',
                    'sort_field': 'query',
                    'sort_order': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__find_attachments
        )

        def __get_attachment(
            self,
            attachment_id,
            **kwargs
        ):
            """Get attachment  # noqa: E501

            Returns information about the attachment identified by id.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_attachment(attachment_id, async_req=True)
            >>> result = thread.get()

            Args:
                attachment_id (str): the id of the attachment

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                AttachmentImpl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['attachment_id'] = \
                attachment_id
            return self.call_with_http_info(**kwargs)

        self.get_attachment = Endpoint(
            settings={
                'response_type': (AttachmentImpl,),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/attachments/{attachmentId}',
                'operation_id': 'get_attachment',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'attachment_id',
                ],
                'required': [
                    'attachment_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'attachment_id':
                        (str,),
                },
                'attribute_map': {
                    'attachment_id': 'attachmentId',
                },
                'location_map': {
                    'attachment_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_attachment
        )

        def __get_attachment_content(
            self,
            attachment_id,
            **kwargs
        ):
            """Get attachment content  # noqa: E501

            Returns content of the attachment identified by given id.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_attachment_content(attachment_id, async_req=True)
            >>> result = thread.get()

            Args:
                attachment_id (str): the id of the attachment

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                file_type
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['attachment_id'] = \
                attachment_id
            return self.call_with_http_info(**kwargs)

        self.get_attachment_content = Endpoint(
            settings={
                'response_type': (file_type,),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/attachments/{attachmentId}/file',
                'operation_id': 'get_attachment_content',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'attachment_id',
                ],
                'required': [
                    'attachment_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'attachment_id':
                        (str,),
                },
                'attribute_map': {
                    'attachment_id': 'attachmentId',
                },
                'location_map': {
                    'attachment_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_attachment_content
        )

        def __remove_attachment(
            self,
            attachment_id,
            **kwargs
        ):
            """Remove attachment  # noqa: E501

            Removes attachment identified by given id.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.remove_attachment(attachment_id, async_req=True)
            >>> result = thread.get()

            Args:
                attachment_id (str): the id of the attachment

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['attachment_id'] = \
                attachment_id
            return self.call_with_http_info(**kwargs)

        self.remove_attachment = Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/attachments/{attachmentId}',
                'operation_id': 'remove_attachment',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'attachment_id',
                ],
                'required': [
                    'attachment_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'attachment_id':
                        (str,),
                },
                'attribute_map': {
                    'attachment_id': 'attachmentId',
                },
                'location_map': {
                    'attachment_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__remove_attachment
        )
