"""
    Collibra Data Governance Center Core API

    <p>The Core REST API allows you to create your own integrations with Collibra Data Governance Center.</p><p><i>Create custom applications to help users get access to the right data.</i></p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from collibra_core.api_client import ApiClient, Endpoint
from collibra_core.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from collibra_core.model.add_relation_type_request import AddRelationTypeRequest
from collibra_core.model.change_relation_type_request import ChangeRelationTypeRequest
from collibra_core.model.relation_type_impl import RelationTypeImpl
from collibra_core.model.relation_type_paged_response import RelationTypePagedResponse


class RelationTypesApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __add_relation_type(
            self,
            **kwargs
        ):
            """Adds a new relation type.  # noqa: E501

            Adds a new relation type.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.add_relation_type(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                add_relation_type_request (AddRelationTypeRequest): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                RelationTypeImpl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.add_relation_type = Endpoint(
            settings={
                'response_type': (RelationTypeImpl,),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/relationTypes',
                'operation_id': 'add_relation_type',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'add_relation_type_request',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'add_relation_type_request':
                        (AddRelationTypeRequest,),
                },
                'attribute_map': {
                },
                'location_map': {
                    'add_relation_type_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__add_relation_type
        )

        def __add_relation_types(
            self,
            **kwargs
        ):
            """Adds multiple new relation type.  # noqa: E501

            Adds multiple new relation type.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.add_relation_types(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                add_relation_type_request ([AddRelationTypeRequest]): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [RelationTypeImpl]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.add_relation_types = Endpoint(
            settings={
                'response_type': ([RelationTypeImpl],),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/relationTypes/bulk',
                'operation_id': 'add_relation_types',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'add_relation_type_request',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'add_relation_type_request':
                        ([AddRelationTypeRequest],),
                },
                'attribute_map': {
                },
                'location_map': {
                    'add_relation_type_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__add_relation_types
        )

        def __change_relation_type(
            self,
            relation_type_id,
            **kwargs
        ):
            """Changes the relation type.  # noqa: E501

            Changes the relation type with the information that is present in the request. Only properties that are specified in this request and have not <code>null</code> values are updated. All other properties are ignored.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.change_relation_type(relation_type_id, async_req=True)
            >>> result = thread.get()

            Args:
                relation_type_id (str): The unique identifier of the relationType

            Keyword Args:
                change_relation_type_request (ChangeRelationTypeRequest): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                RelationTypeImpl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['relation_type_id'] = \
                relation_type_id
            return self.call_with_http_info(**kwargs)

        self.change_relation_type = Endpoint(
            settings={
                'response_type': (RelationTypeImpl,),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/relationTypes/{relationTypeId}',
                'operation_id': 'change_relation_type',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'relation_type_id',
                    'change_relation_type_request',
                ],
                'required': [
                    'relation_type_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'relation_type_id':
                        (str,),
                    'change_relation_type_request':
                        (ChangeRelationTypeRequest,),
                },
                'attribute_map': {
                    'relation_type_id': 'relationTypeId',
                },
                'location_map': {
                    'relation_type_id': 'path',
                    'change_relation_type_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__change_relation_type
        )

        def __change_relation_types(
            self,
            **kwargs
        ):
            """Changes the relation types.  # noqa: E501

            Changes the relation types with the information that is present in the request. Only properties that are specified in this request and have not <code>null</code> values are updated. All other properties are ignored.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.change_relation_types(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                change_relation_type_request ([ChangeRelationTypeRequest]): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                [RelationTypeImpl]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.change_relation_types = Endpoint(
            settings={
                'response_type': ([RelationTypeImpl],),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/relationTypes/bulk',
                'operation_id': 'change_relation_types',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'change_relation_type_request',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'change_relation_type_request':
                        ([ChangeRelationTypeRequest],),
                },
                'attribute_map': {
                },
                'location_map': {
                    'change_relation_type_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__change_relation_types
        )

        def __find_relation_types(
            self,
            **kwargs
        ):
            """Finds all the relation types matching the given criteria.  # noqa: E501

            Returns relation types matching the given search criteria. Only parameters that are specified in this request and have not <code>null</code> values are used for filtering. All other parameters are ignored. The returned relation types satisfy all constraints that are specified in this search criteria. By default a result containing 1000 relation types is returned.   # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.find_relation_types(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                offset (int): The first result to retrieve. If not set (offset = <code>0</code>), results will be retrieved starting from row <code>0</code>.. [optional] if omitted the server will use the default value of 0
                limit (int): The maximum number of results to retrieve. If not set (limit = <code>0</code>), the default limit will be used.. [optional] if omitted the server will use the default value of 0
                source_type_id (str): The ID of the source type of the relation type to search for.. [optional]
                source_type_name (str): The name of the source type of the relation type to search for.. [optional]
                role (str): The name of the role that the source plays to search for.. [optional]
                target_type_id (str): The ID of the target type of the relation type to search for.. [optional]
                target_type_name (str): The name of the target type of the relation type to search for.. [optional]
                co_role (str): The name of the role that the target plays to search for.. [optional]
                sort_field (str): The field that should be used as reference for sorting.. [optional] if omitted the server will use the default value of "ROLE"
                sort_order (str): The order of sorting.. [optional] if omitted the server will use the default value of "ASC"
                role_co_role_logical_operator (str): The logical operator determining how to combine the role and coRole criteria: AND or OR.. [optional] if omitted the server will use the default value of "AND"
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                RelationTypePagedResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.find_relation_types = Endpoint(
            settings={
                'response_type': (RelationTypePagedResponse,),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/relationTypes',
                'operation_id': 'find_relation_types',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'offset',
                    'limit',
                    'source_type_id',
                    'source_type_name',
                    'role',
                    'target_type_id',
                    'target_type_name',
                    'co_role',
                    'sort_field',
                    'sort_order',
                    'role_co_role_logical_operator',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                    'sort_field',
                    'sort_order',
                    'role_co_role_logical_operator',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('sort_field',): {

                        "ROLE": "ROLE",
                        "CO_ROLE": "CO_ROLE"
                    },
                    ('sort_order',): {

                        "ASC": "ASC",
                        "DESC": "DESC"
                    },
                    ('role_co_role_logical_operator',): {

                        "AND": "AND",
                        "OR": "OR"
                    },
                },
                'openapi_types': {
                    'offset':
                        (int,),
                    'limit':
                        (int,),
                    'source_type_id':
                        (str,),
                    'source_type_name':
                        (str,),
                    'role':
                        (str,),
                    'target_type_id':
                        (str,),
                    'target_type_name':
                        (str,),
                    'co_role':
                        (str,),
                    'sort_field':
                        (str,),
                    'sort_order':
                        (str,),
                    'role_co_role_logical_operator':
                        (str,),
                },
                'attribute_map': {
                    'offset': 'offset',
                    'limit': 'limit',
                    'source_type_id': 'sourceTypeId',
                    'source_type_name': 'sourceTypeName',
                    'role': 'role',
                    'target_type_id': 'targetTypeId',
                    'target_type_name': 'targetTypeName',
                    'co_role': 'coRole',
                    'sort_field': 'sortField',
                    'sort_order': 'sortOrder',
                    'role_co_role_logical_operator': 'roleCoRoleLogicalOperator',
                },
                'location_map': {
                    'offset': 'query',
                    'limit': 'query',
                    'source_type_id': 'query',
                    'source_type_name': 'query',
                    'role': 'query',
                    'target_type_id': 'query',
                    'target_type_name': 'query',
                    'co_role': 'query',
                    'sort_field': 'query',
                    'sort_order': 'query',
                    'role_co_role_logical_operator': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__find_relation_types
        )

        def __get_relation_type(
            self,
            relation_type_id,
            **kwargs
        ):
            """Returns relation type identified by given UUID.  # noqa: E501

            Returns relation type identified by given UUID.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_relation_type(relation_type_id, async_req=True)
            >>> result = thread.get()

            Args:
                relation_type_id (str): The unique identifier of the relationType

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                RelationTypeImpl
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['relation_type_id'] = \
                relation_type_id
            return self.call_with_http_info(**kwargs)

        self.get_relation_type = Endpoint(
            settings={
                'response_type': (RelationTypeImpl,),
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/relationTypes/{relationTypeId}',
                'operation_id': 'get_relation_type',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'relation_type_id',
                ],
                'required': [
                    'relation_type_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'relation_type_id':
                        (str,),
                },
                'attribute_map': {
                    'relation_type_id': 'relationTypeId',
                },
                'location_map': {
                    'relation_type_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_relation_type
        )

        def __remove_relation_type(
            self,
            relation_type_id,
            **kwargs
        ):
            """Removes relation type identified by given UUID.  # noqa: E501

            Removes relation type identified by given UUID.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.remove_relation_type(relation_type_id, async_req=True)
            >>> result = thread.get()

            Args:
                relation_type_id (str): The unique identifier of the relationType

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['relation_type_id'] = \
                relation_type_id
            return self.call_with_http_info(**kwargs)

        self.remove_relation_type = Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/relationTypes/{relationTypeId}',
                'operation_id': 'remove_relation_type',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'relation_type_id',
                ],
                'required': [
                    'relation_type_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'relation_type_id':
                        (str,),
                },
                'attribute_map': {
                    'relation_type_id': 'relationTypeId',
                },
                'location_map': {
                    'relation_type_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__remove_relation_type
        )

        def __remove_relation_types(
            self,
            **kwargs
        ):
            """Removes multiple relation types.  # noqa: E501

            Removes multiple relation types identified by the UUIDs passed as parameter.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.remove_relation_types(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                request_body ([str]): The unique identifiers of the relationTypes. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.remove_relation_types = Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'basicAuth'
                ],
                'endpoint_path': '/relationTypes/bulk',
                'operation_id': 'remove_relation_types',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'request_body',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'request_body':
                        ([str],),
                },
                'attribute_map': {
                },
                'location_map': {
                    'request_body': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__remove_relation_types
        )
